[tool.black]

line-length = 120

[tool.pytest.ini_options]

testpaths = ["tests"]

[tool.pylint.'MASTER']

jobs = 0
ignore = '''
    .git, 
    __pycache__
'''

[tool.pylint.'REFACTORING']

max-nested-blocks = 8

[tool.pylint.'FORMAT']

max-line-length = 120
expected-line-ending-format = "LF"

[tool.pylint.'BASIC']

bad-names = '''
    foo, 
    bar, 
    baz, 
    info, 
'''

[tool.pylint.'DESIGN']

max-args = 10
max-attributes = 15
max-bool-expr = 5
max-branches = 12
max-locals = 15
max-parents = 7
max-public-methods = 20
max-returns = 6
max-statements = 50
min-public-methods = 2
max-module-lines = 3000

[tool.pylint.'MESSAGES CONTROL']

disable = '''
    c-extension-no-member,
    missing-module-docstring, 
    missing-class-docstring, 
    missing-function-docstring,
    consider-using-dict-items,
    fixme,
'''
